### ISSUE TITLE
Stereo multiplexing

### ISSUE THREAD

**Issue by miloszszymczak** [Emerica/pifm#1]
It would be nice to add stereo multiplexing.

**Comment by Emerica** [comment]
## Please see - http://www.icrobotics.co.uk/wiki/index.php/Turning_the_Raspberry_Pi_Into_an_FM_Transmitter

The plan was to make a kernel mode driver that would be able to use the DMA controller to offload the CPU and play smooth music without loading the CPU, but we ran out of time.

## If you're v. smart, you might be able to get stereo going!

This is just a forked version with a couple changes so you can change the frequency / power levels.
I don't currently have the time/knowledge to dive into  the above.
Sorry.
